spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fcbarca1899
    url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
  jpa:
    show-sql: true
    open-in-view: true
server:
  port: 8090
